In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.read_csv("Medical student Csv.csv")

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
0,2,18,1,1,120,1,0,56,3,0,88,62,27,17,0.738095,34,61,17,13,20
1,4,26,4,1,1,1,0,20,4,0,109,55,37,22,0.690476,7,33,14,11,26
2,9,21,3,2,1,0,0,36,3,0,106,64,39,17,0.690476,25,73,24,7,23
3,10,21,2,2,1,0,1,51,5,0,101,52,33,18,0.833333,17,48,16,10,21
4,13,21,3,1,1,1,0,22,4,0,102,58,28,21,0.690476,14,46,22,14,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,1781,21,2,1,1,1,0,45,3,0,106,63,39,28,0.619048,41,39,23,4,34
882,1785,20,2,2,1,0,0,13,3,0,113,67,40,21,0.809524,26,41,17,5,24
883,1787,19,1,1,1,0,0,50,5,0,100,50,31,24,0.547619,14,45,15,8,31
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19
885,1790,22,3,1,1,0,1,20,5,0,102,54,26,25,0.571429,5,27,11,9,30

In [7]:
#saving the Dataframe to a variable, df
df=pd.read_csv("Medical student Csv.csv")

In [11]:
#making a copy of the variable incase of a data lose
Data=df.copy()

In [117]:
Q1=df.groupby("Satisfaction with health")["age"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["age"].quantile(0.75)
IQR=Q3-Q1
outliers_age = df[
    (df["age"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["age"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_age[["Satisfaction with health","age"]]

     Satisfaction with health  age
45                          2   29
48                          3   32
54                          4   32
60                          3   37
76                          5   31
163                         4   32
278                         3   35
316                         2   29
322                         2   29
385                         5   33
393                         3   35
417                         5   49
432                         4   37
453                         4   31
520                         1   44
523                         4   32
529                         1   34
531                         4   33
564                         4   32
571                         2   39
629                         4   32
676                         3   31
737                         3   38
771                         3   37
774                         5   35
859                         4   32
871                         3   34

In [157]:
n0_outlier_age= df[
    (df["age"] >(Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) &
    (df["age"] <(Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
n0_outlier_age

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
0,2,18,1,1,120,1,0,56,3,0,88,62,27,17,0.738095,34,61,17,13,20
1,4,26,4,1,1,1,0,20,4,0,109,55,37,22,0.690476,7,33,14,11,26
2,9,21,3,2,1,0,0,36,3,0,106,64,39,17,0.690476,25,73,24,7,23
3,10,21,2,2,1,0,1,51,5,0,101,52,33,18,0.833333,17,48,16,10,21
4,13,21,3,1,1,1,0,22,4,0,102,58,28,21,0.690476,14,46,22,14,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,1781,21,2,1,1,1,0,45,3,0,106,63,39,28,0.619048,41,39,23,4,34
882,1785,20,2,2,1,0,0,13,3,0,113,67,40,21,0.809524,26,41,17,5,24
883,1787,19,1,1,1,0,0,50,5,0,100,50,31,24,0.547619,14,45,15,8,31
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19
885,1790,22,3,1,1,0,1,20,5,0,102,54,26,25,0.571429,5,27,11,9,30

In [191]:
df=n0_outlier_age
df

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
0,2,18,1,1,120,1,0,56,3,0,88,62,27,17,0.738095,34,61,17,13,20
1,4,26,4,1,1,1,0,20,4,0,109,55,37,22,0.690476,7,33,14,11,26
2,9,21,3,2,1,0,0,36,3,0,106,64,39,17,0.690476,25,73,24,7,23
3,10,21,2,2,1,0,1,51,5,0,101,52,33,18,0.833333,17,48,16,10,21
4,13,21,3,1,1,1,0,22,4,0,102,58,28,21,0.690476,14,46,22,14,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,1781,21,2,1,1,1,0,45,3,0,106,63,39,28,0.619048,41,39,23,4,34
882,1785,20,2,2,1,0,0,13,3,0,113,67,40,21,0.809524,26,41,17,5,24
883,1787,19,1,1,1,0,0,50,5,0,100,50,31,24,0.547619,14,45,15,8,31
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19
885,1790,22,3,1,1,0,1,20,5,0,102,54,26,25,0.571429,5,27,11,9,30

In [165]:
Q1=df.groupby("Satisfaction with health")["year"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["year"].quantile(0.75)
IQR=Q3-Q1
outliers_year = df[
    (df["year"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["year"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_year[["Satisfaction with health","year"]]

Empty DataFrame
Columns: [Satisfaction with health, year]
Index: []

In [167]:
Q1=df.groupby("Satisfaction with health")["sex"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["sex"].quantile(0.75)
IQR=Q3-Q1
outliers_sex = df[
    (df["sex"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["sex"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_sex[["Satisfaction with health","sex"]]

     Satisfaction with health  sex
0                           3    1
52                          3    1
111                         3    1
176                         3    1
180                         3    1
255                         3    1
261                         3    1
268                         3    1
284                         3    1
303                         3    1
306                         3    1
410                         3    1
418                         3    1
430                         3    1
464                         3    1
470                         3    1
550                         3    1
572                         3    1
575                         3    3
583                         3    1
600                         3    3
607                         3    1
624                         3    1
645                         3    1
720                         3    1
739                         3    1
750                         3    1
833                         3    1
837                         3    1
877                         3    1
881                         3    1

In [171]:
 n0_outlier_sex=df[
    (df["sex"] > (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) &
    (df["sex"] < (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
n0_outlier_sex

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
1,4,26,4,1,1,1,0,20,4,0,109,55,37,22,0.690476,7,33,14,11,26
3,10,21,2,2,1,0,1,51,5,0,101,52,33,18,0.833333,17,48,16,10,21
4,13,21,3,1,1,1,0,22,4,0,102,58,28,21,0.690476,14,46,22,14,23
5,14,26,5,2,1,1,1,10,2,0,102,48,37,17,0.690476,14,56,18,15,18
7,21,23,4,1,1,1,1,8,4,0,118,65,40,32,0.880952,6,36,11,10,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1779,27,6,2,1,1,0,5,2,0,112,66,30,26,0.690476,24,33,20,7,25
880,1780,20,2,2,1,1,0,20,5,0,109,61,37,16,0.738095,3,32,13,5,29
883,1787,19,1,1,1,0,0,50,5,0,100,50,31,24,0.547619,14,45,15,8,31
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19
885,1790,22,3,1,1,0,1,20,5,0,102,54,26,25,0.571429,5,27,11,9,30

In [173]:
df=n0_outlier_sex

In [175]:
df

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
1,4,26,4,1,1,1,0,20,4,0,109,55,37,22,0.690476,7,33,14,11,26
3,10,21,2,2,1,0,1,51,5,0,101,52,33,18,0.833333,17,48,16,10,21
4,13,21,3,1,1,1,0,22,4,0,102,58,28,21,0.690476,14,46,22,14,23
5,14,26,5,2,1,1,1,10,2,0,102,48,37,17,0.690476,14,56,18,15,18
7,21,23,4,1,1,1,1,8,4,0,118,65,40,32,0.880952,6,36,11,10,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1779,27,6,2,1,1,0,5,2,0,112,66,30,26,0.690476,24,33,20,7,25
880,1780,20,2,2,1,1,0,20,5,0,109,61,37,16,0.738095,3,32,13,5,29
883,1787,19,1,1,1,0,0,50,5,0,100,50,31,24,0.547619,14,45,15,8,31
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19
885,1790,22,3,1,1,0,1,20,5,0,102,54,26,25,0.571429,5,27,11,9,30

In [241]:
Q1=df.groupby("Satisfaction with health")["Partnership Status"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["Partnership Status"].quantile(0.75)
IQR=Q3-Q1
outliers_Partner = df[
    (df["Partnership Status"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["Partnership Status"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_Partner[['Satisfaction with health',"Partnership Status"]]

Empty DataFrame
Columns: [Satisfaction with health, Partnership Status]
Index: []

In [247]:
Q1=df.groupby("Satisfaction with health")["Job Status"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["Job Status"].quantile(0.75)
IQR=Q3-Q1
outliers_Job = df[
    (df["Job Status"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["Job Status"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_Job[['Satisfaction with health',"Job Status"]]

Empty DataFrame
Columns: [Satisfaction with health, Job Status]
Index: []

In [219]:
no_outliers_Mother= df[
    (df["Mother Tongue"] > (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) &
    (df["Mother Tongue"] < (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
no_outliers_Mother[["Satisfaction with health","Mother Tongue"]]

Empty DataFrame
Columns: [Satisfaction with health, Mother Tongue]
Index: []

In [249]:
Q1=df.groupby("Satisfaction with health")["Hrs of study/week"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["Hrs of study/week"].quantile(0.75)
IQR=Q3-Q1
outliers_Hrs = df[
    (df["Hrs of study/week"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["Hrs of study/week"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_Hrs[['Satisfaction with health',"Hrs of study/week"]]

Empty DataFrame
Columns: [Satisfaction with health, Hrs of study/week]
Index: []

In [251]:
Q1=df.groupby("Satisfaction with health")["Visit to Psychiatrist"].quantile(0.25)
Q3=df.groupby("Satisfaction with health")["Visit to Psychiatrist"].quantile(0.75)
IQR=Q3-Q1
outliers_Psy = df[
    (df["Visit to Psychiatrist"] < (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) |
    (df["Visit to Psychiatrist"] > (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
outliers_Psy[['Satisfaction with health',"Visit to Psychiatrist"]]

     Satisfaction with health  Visit to Psychiatrist
11                          5                      1
20                          4                      1
22                          4                      1
23                          4                      1
24                          4                      1
..                        ...                    ...
808                         4                      1
843                         4                      1
854                         4                      1
863                         4                      1
874                         4                      1

[120 rows x 2 columns]

In [255]:
no_outlier_psy=df[
    (df["Visit to Psychiatrist"] > (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) &
    (df["Visit to Psychiatrist"] < (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
no_outlier_psy

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
0,2,18,1,1,120,1,0,56,3,0,88,62,27,17,0.738095,34,61,17,13,20
2,9,21,3,2,1,0,0,36,3,0,106,64,39,17,0.690476,25,73,24,7,23
5,14,26,5,2,1,1,1,10,2,0,102,48,37,17,0.690476,14,56,18,15,18
6,17,23,5,2,1,1,0,15,3,0,117,58,38,23,0.714286,45,56,28,17,16
8,23,23,4,2,1,1,1,20,2,0,118,69,46,23,0.666667,43,43,26,21,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,1777,22,4,2,1,1,0,25,3,1,115,65,41,24,0.714286,16,44,17,9,24
879,1779,27,6,2,1,1,0,5,2,0,112,66,30,26,0.690476,24,33,20,7,25
881,1781,21,2,1,1,1,0,45,3,0,106,63,39,28,0.619048,41,39,23,4,34
882,1785,20,2,2,1,0,0,13,3,0,113,67,40,21,0.809524,26,41,17,5,24
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19

In [257]:
no_outlier_psy=df[
    (df["Visit to Psychiatrist"] > (Q1[df['Satisfaction with health']].values - 1.5 * IQR[df['Satisfaction with health']].values)) &
    (df["Visit to Psychiatrist"] < (Q3[df['Satisfaction with health']].values + 1.5 * IQR[df['Satisfaction with health']].values))
]
no_outlier_psy[['Satisfaction with health',"Visit to Psychiatrist"]]

     Satisfaction with health  Visit to Psychiatrist
0                           3                      0
2                           3                      0
5                           2                      0
6                           3                      0
8                           2                      0
..                        ...                    ...
878                         3                      1
879                         2                      0
881                         3                      0
882                         3                      0
884                         2                      1

[211 rows x 2 columns]

In [259]:
df=no_outlier_psy

In [261]:
df

,id,age,year,sex,Mother Tongue,Partnership Status,Job Status,Hrs of study/week,Satisfaction with health,Visit to Psychiatrist,Total empathy score,Cognitive empathy score,QCAE Affective Empathy score,AMSP total Score,Mean Value of responses,D total score,STAI score,Emotional Exhaution,mbi_cynicism,mbi_Academic Efficacy
0,2,18,1,1,120,1,0,56,3,0,88,62,27,17,0.738095,34,61,17,13,20
2,9,21,3,2,1,0,0,36,3,0,106,64,39,17,0.690476,25,73,24,7,23
5,14,26,5,2,1,1,1,10,2,0,102,48,37,17,0.690476,14,56,18,15,18
6,17,23,5,2,1,1,0,15,3,0,117,58,38,23,0.714286,45,56,28,17,16
8,23,23,4,2,1,1,1,20,2,0,118,69,46,23,0.666667,43,43,26,21,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,1777,22,4,2,1,1,0,25,3,1,115,65,41,24,0.714286,16,44,17,9,24
879,1779,27,6,2,1,1,0,5,2,0,112,66,30,26,0.690476,24,33,20,7,25
881,1781,21,2,1,1,1,0,45,3,0,106,63,39,28,0.619048,41,39,23,4,34
882,1785,20,2,2,1,0,0,13,3,0,113,67,40,21,0.809524,26,41,17,5,24
884,1789,24,5,2,1,0,0,20,2,1,120,64,39,21,0.785714,33,58,22,15,19