In [1]:
import numpy as np
import pandas as pd

In [5]:
# loading the dataframe
df=pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# making a copy
data=df.copy()
data

In [15]:
# checking number rows and colums
df.shape

(1000, 8)

In [17]:
# checking for empty rows and colums
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [21]:
# checking if the datatypes and general info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [29]:
# checking for datatypes alone
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [31]:
# checking the statistics of our dataframe
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [43]:
# determine the average score and round up to 2 dp
Avrg=((df["math score"]+ df["reading score"]+df["writing score"])/3).round(2)
Avrg

0      72.67
1      82.33
2      92.67
3      49.33
4      76.33
       ...
995    94.00
996    57.33
997    65.00
998    74.33
999    83.00
Length: 1000, dtype: float64

In [47]:
# create a column a column called average and save the average
df["Average"]=Avrg
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

In [52]:
df.drop(columns=["Average"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [56]:
# for example a score was ommitted, let us then add it and give them a random score using the numpy function
df["English Language score"]=78
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average,English Language score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67,78
1,female,group C,some college,standard,completed,69,90,88,82.33,78
2,female,group B,master's degree,standard,none,90,95,93,92.67,78
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33,78
4,male,group C,some college,standard,none,76,78,75,76.33,78
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00,78
996,male,group C,high school,free/reduced,none,62,55,55,57.33,78
997,female,group C,high school,free/reduced,completed,59,71,65,65.00,78
998,female,group D,some college,standard,completed,68,78,77,74.33,78
999,female,group D,some college,free/reduced,none,77,86,86,83.00,78

In [ ]:
# but it is impossible for everybody to have a score of 78 so we random and array
np.arange(0,1000)

In [60]:
# lenght of the array from 0-1000
len(np.arange(0,1000))

1000

In [68]:
# create a new column and also make a random number then save on the new column
df["English Language score"]=np.random.randint(0,100,size=1000)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average,English Language score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67,13
1,female,group C,some college,standard,completed,69,90,88,82.33,4
2,female,group B,master's degree,standard,none,90,95,93,92.67,78
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33,24
4,male,group C,some college,standard,none,76,78,75,76.33,35
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00,46
996,male,group C,high school,free/reduced,none,62,55,55,57.33,90
997,female,group C,high school,free/reduced,completed,59,71,65,65.00,31
998,female,group D,some college,standard,completed,68,78,77,74.33,3
999,female,group D,some college,free/reduced,none,77,86,86,83.00,52

In [70]:
# dropping the column which was created for illustration purpose
df.drop(columns=["English Language score"])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

In [72]:
#setting the dataframe to display full lenght of column
pd.set_option("display.max_rows",None)

In [ ]:
df

In [76]:
#reverting to normal
pd.reset_option("display.max_rows")

In [78]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average,English Language score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67,13
1,female,group C,some college,standard,completed,69,90,88,82.33,4
2,female,group B,master's degree,standard,none,90,95,93,92.67,78
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33,24
4,male,group C,some college,standard,none,76,78,75,76.33,35
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00,46
996,male,group C,high school,free/reduced,none,62,55,55,57.33,90
997,female,group C,high school,free/reduced,completed,59,71,65,65.00,31
998,female,group D,some college,standard,completed,68,78,77,74.33,3
999,female,group D,some college,free/reduced,none,77,86,86,83.00,52

In [90]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

In [92]:
#ascertain the gender value counts for the exam
df["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [100]:
#parental level of education value count
df["parental level of education"].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [102]:
#ascertain the lunch value count
df["lunch"].value_counts()

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [104]:
#test preparation value count
df["test preparation course"].value_counts()

test preparation course
none         642
completed    358
Name: count, dtype: int64

In [114]:
#reducing the columns on the dataframe
df[["gender","lunch","test preparation course","Average" ]]

     gender         lunch test preparation course  Average
0    female      standard                    none    72.67
1    female      standard               completed    82.33
2    female      standard                    none    92.67
3      male  free/reduced                    none    49.33
4      male      standard                    none    76.33
..      ...           ...                     ...      ...
995  female      standard               completed    94.00
996    male  free/reduced                    none    57.33
997  female  free/reduced               completed    65.00
998  female      standard               completed    74.33
999  female  free/reduced                    none    83.00

[1000 rows x 4 columns]

In [320]:
df[["gender","lunch","test preparation course","Average" ]].sort_values("lunch").head(10)

     gender         lunch test preparation course  Average
999  female  free/reduced                    none    83.00
363  female  free/reduced                    none    31.00
757    male  free/reduced               completed    70.00
758  female  free/reduced               completed    58.67
760  female  free/reduced                    none    63.00
358    male  free/reduced                    none    60.67
357  female  free/reduced               completed    59.00
348    male  free/reduced                    none    71.67
769    male  free/reduced                    none    58.33
772  female  free/reduced               completed    63.67

In [334]:
#saving to a variable
df_sort=df[["gender","lunch","test preparation course","Average" ]].sort_values("Average")
df_sort.head(100)

     gender         lunch test preparation course  Average
59   female  free/reduced                    none     9.00
980  female  free/reduced                    none    18.33
596    male  free/reduced                    none    23.00
327    male  free/reduced                    none    23.33
76     male      standard                    none    26.00
..      ...           ...                     ...      ...
307    male      standard                    none    49.00
575    male  free/reduced               completed    49.33
9    female  free/reduced                    none    49.33
174  female  free/reduced               completed    49.33
3      male  free/reduced                    none    49.33

[100 rows x 4 columns]

In [ ]:
#displaying full lenght of row
pd.set_option("display.max_rows",None)
df_sort

In [142]:
#reverting to normal
pd.reset_option("display.max_rows")

In [144]:
df_sort

     gender         lunch test preparation course  Average
59   female  free/reduced                    none     9.00
980  female  free/reduced                    none    18.33
596    male  free/reduced                    none    23.00
327    male  free/reduced                    none    23.33
76     male      standard                    none    26.00
..      ...           ...                     ...      ...
179  female      standard               completed    99.00
114  female      standard               completed    99.67
458  female      standard                    none   100.00
916    male      standard               completed   100.00
962  female      standard                    none   100.00

[1000 rows x 4 columns]

In [354]:
#displaying test preparation column==none and saving to a variable
df_test_none=df_sort[df_sort["test preparation course"]=="none"]
df_test_none

     gender         lunch test preparation course  Average
59   female  free/reduced                    none     9.00
980  female  free/reduced                    none    18.33
596    male  free/reduced                    none    23.00
327    male  free/reduced                    none    23.33
76     male      standard                    none    26.00
..      ...           ...                     ...      ...
855  female      standard                    none    96.67
957  female      standard                    none    97.33
712  female      standard                    none    99.00
458  female      standard                    none   100.00
962  female      standard                    none   100.00

[642 rows x 4 columns]

In [380]:
import matplotlib as plt
df_test_male=df_test_none[df_test_none["gender"]=="male"]
df_test_male

    gender         lunch test preparation course  Average
596   male  free/reduced                    none    23.00
327   male  free/reduced                    none    23.33
76    male      standard                    none    26.00
211   male  free/reduced                    none    30.00
896   male  free/reduced                    none    30.67
..     ...           ...                     ...      ...
16    male      standard                    none    87.67
34    male      standard                    none    88.67
689   male  free/reduced                    none    88.67
571   male      standard                    none    93.00
864   male      standard                    none    93.67

[308 rows x 4 columns]

In [412]:
df_test_male.loc[(df_test_male["Average"]>=50)]

    gender         lunch test preparation course  Average
153   male      standard                    none    50.00
869   male  free/reduced                    none    50.33
22    male      standard                    none    50.33
628   male  free/reduced                    none    50.67
834   male      standard                    none    51.00
..     ...           ...                     ...      ...
16    male      standard                    none    87.67
34    male      standard                    none    88.67
689   male  free/reduced                    none    88.67
571   male      standard                    none    93.00
864   male      standard                    none    93.67

[257 rows x 4 columns]

In [392]:
df_test_none[["gender","lunch","Average"]].value_counts()

gender  lunch     Average
male    standard  73.33      5
female  standard  74.33      5
                  68.67      5
                  66.67      5
                  70.33      5
                            ..
                  80.67      1
                  80.33      1
                  80.00      1
                  79.00      1
male    standard  93.67      1
Name: count, Length: 393, dtype: int64

In [292]:
#statistics of the variable from above
df_test_none.describe()

          Average
count  642.000000
mean    65.038801
std     14.186568
min      9.000000
25%     55.415000
50%     65.330000
75%     75.000000
max    100.000000

In [250]:
#info
df_test_none.info()

<class 'pandas.core.frame.DataFrame'>
Index: 642 entries, 59 to 962
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   642 non-null    object
 1   lunch                    642 non-null    object
 2   test preparation course  642 non-null    object
 3   Average                  642 non-null    float64
dtypes: float64(1), object(3)
memory usage: 25.1+ KB

In [252]:
#displaying test preparation column==completed and saving to a variable
df_test_completed=df_sort[df_sort["test preparation course"]=="completed"]
df_test_completed

     gender         lunch test preparation course  Average
842  female  free/reduced               completed    34.33
683  female  free/reduced               completed    37.67
862    male  free/reduced               completed    39.67
902  female  free/reduced               completed    41.00
785  female      standard               completed    42.33
..      ...           ...                     ...      ...
165  female      standard               completed    98.67
625    male      standard               completed    98.67
179  female      standard               completed    99.00
114  female      standard               completed    99.67
916    male      standard               completed   100.00

[358 rows x 4 columns]

In [254]:
#info
df_test_completed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 358 entries, 842 to 916
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   358 non-null    object
 1   lunch                    358 non-null    object
 2   test preparation course  358 non-null    object
 3   Average                  358 non-null    float64
dtypes: float64(1), object(3)
memory usage: 14.0+ KB

In [264]:
#displaying lunch column==free/reduced and saving to a variable
df_lunch_free=df_sort[df_sort["lunch"]=="free/reduced"]
df_lunch_free

     gender         lunch test preparation course  Average
59   female  free/reduced                    none     9.00
980  female  free/reduced                    none    18.33
596    male  free/reduced                    none    23.00
327    male  free/reduced                    none    23.33
17   female  free/reduced                    none    26.00
..      ...           ...                     ...      ...
514  female  free/reduced               completed    89.33
377  female  free/reduced               completed    93.33
566  female  free/reduced               completed    97.33
149    male  free/reduced               completed    97.67
903  female  free/reduced               completed    97.67

[355 rows x 4 columns]

In [266]:
#info
df_lunch_free.info()

<class 'pandas.core.frame.DataFrame'>
Index: 355 entries, 59 to 903
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   355 non-null    object
 1   lunch                    355 non-null    object
 2   test preparation course  355 non-null    object
 3   Average                  355 non-null    float64
dtypes: float64(1), object(3)
memory usage: 13.9+ KB

In [268]:
#displaying lunch column==standard and saving to a variable
df_lunch_stD=df_sort[df_sort["lunch"]=="standard"]
df_lunch_stD

     gender     lunch test preparation course  Average
76     male  standard                    none    26.00
601  female  standard                    none    29.33
787  female  standard                    none    29.67
706    male  standard                    none    38.67
810    male  standard                    none    39.33
..      ...       ...                     ...      ...
179  female  standard               completed    99.00
114  female  standard               completed    99.67
458  female  standard                    none   100.00
916    male  standard               completed   100.00
962  female  standard                    none   100.00

[645 rows x 4 columns]

In [270]:
#info
df_lunch_stD.info()

<class 'pandas.core.frame.DataFrame'>
Index: 645 entries, 76 to 962
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   645 non-null    object
 1   lunch                    645 non-null    object
 2   test preparation course  645 non-null    object
 3   Average                  645 non-null    float64
dtypes: float64(1), object(3)
memory usage: 25.2+ KB

In [284]:
#displaying lunchcolumn==free/reduced and test preparation column==none 
df_test_none.loc[(df_test_none["lunch"]=="free/reduced") & (df_test_none["test preparation course"]=="none")]

     gender         lunch test preparation course  Average
59   female  free/reduced                    none     9.00
980  female  free/reduced                    none    18.33
596    male  free/reduced                    none    23.00
327    male  free/reduced                    none    23.33
17   female  free/reduced                    none    26.00
..      ...           ...                     ...      ...
861  female  free/reduced                    none    84.67
463  female  free/reduced                    none    86.00
821  female  free/reduced                    none    87.00
873    male  free/reduced                    none    87.33
689    male  free/reduced                    none    88.67

[224 rows x 4 columns]

In [288]:
#displaying lunchcolumn==standard and test preparation column==completed 
df_test_completed.loc[(df_test_completed["lunch"]=="standard") & (df_test_completed["test preparation course"]=="completed")]

     gender     lunch test preparation course  Average
785  female  standard               completed    42.33
296    male  standard               completed    43.33
978    male  standard               completed    48.00
250    male  standard               completed    48.33
136    male  standard               completed    48.67
..      ...       ...                     ...      ...
165  female  standard               completed    98.67
625    male  standard               completed    98.67
179  female  standard               completed    99.00
114  female  standard               completed    99.67
916    male  standard               completed   100.00

[227 rows x 4 columns]

In [302]:
# getting backthe dataframe for df_sort and sorting in descending order
df_ascending=df_sort.sort_values("Average", ascending=False).head(10)
df_ascending

     gender         lunch test preparation course  Average
962  female      standard                    none   100.00
916    male      standard               completed   100.00
458  female      standard                    none   100.00
114  female      standard               completed    99.67
179  female      standard               completed    99.00
712  female      standard                    none    99.00
625    male      standard               completed    98.67
165  female      standard               completed    98.67
685  female      standard               completed    97.67
903  female  free/reduced               completed    97.67

In [304]:
#displaying only gender and average clumn
df_ascending[["gender","Average"]]

     gender  Average
962  female   100.00
916    male   100.00
458  female   100.00
114  female    99.67
179  female    99.00
712  female    99.00
625    male    98.67
165  female    98.67
685  female    97.67
903  female    97.67